### ISSUE TITLE
连接Oracle数据库后报异常,数据导出界面无法显示

### ISSUE THREAD

**Issue by dmh1996** [Zhuoyuan1/EasyDataBaseExport#3]
严重: java.lang.NoClassDefFoundError: javafx/util/Pair
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2673)
	at java.desktop/java.awt.Component.isCoalesceEventsOverriden(Component.java:6311)
	at java.desktop/java.awt.Component$3.run(Component.java:6265)
	at java.desktop/java.awt.Component$3.run(Component.java:6263)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Component.checkCoalescing(Component.java:6262)
	at java.desktop/java.awt.Component.<init>(Component.java:6230)
	at java.desktop/java.awt.Container.<init>(Container.java:300)
	at java.desktop/javax.swing.JComponent.<init>(JComponent.java:640)
	at java.desktop/javax.swing.JTree.<init>(JTree.java:718)
	at java.desktop/javax.swing.JTree.<init>(JTree.java:707)
	at java.desktop/javax.swing.JTree.<init>(JTree.java:691)
	at com.easydatabaseexport.ui.component.JCheckBoxTree.<init>(JCheckBoxTree.java:61)
	at com.easydatabaseexport.ui.ConnectJavaFrame.mainFrame(ConnectJavaFrame.java:104)
	at com.easydatabaseexport.ui.IndexJavaFrame$1.lambda$run$0(IndexJavaFrame.java:282)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 41 more

**Comment by dmh1996** [comment]
使用1.8版本的jdk后解决
